version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    volumes:
      - /home/bhanureddy/reverse_proxy/reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    network_mode: "host"
